export {default as HeadphoneOneOne} from "./HeadphoneOneFirst.svg";
export {default as HeadphoneOneTwo} from "./HeadphoneOneSecond.svg";
export {default as HeadphoneOneThree} from "./HeadphoneOneThird.svg";
export {default as HeadphoneTwoOne} from "./HeadphoneTwoFirst.svg";
export {default as HeadphoneTwoTwo} from "./HeadphoneTwoSecond.svg";
export {default as HeadphoneTwoThree} from "./HeadphoneTwoThird.svg";
export {default as HeadphoneThreeOne} from "./HeadphoneThreeFirst.svg";
export {default as HeadphoneThreeTwo} from "./HeadphoneThreeSecond.svg";
export {default as HeadphoneThreeThree} from "./HeadphoneThreeThird.svg";